/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-menu-item` | `/add-menu-item`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create-user` | `/create-user`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/edit-menu-item` | `/edit-menu-item`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/manage-users` | `/manage-users`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/order-history` | `/order-history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ongoing-orders` | `/ongoing-orders`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/kitchen`; params?: Router.UnknownInputParams; } | { pathname: `/edit-order/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/checkout`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/add-menu-item` | `/add-menu-item`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/create-user` | `/create-user`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/edit-menu-item` | `/edit-menu-item`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/manage-users` | `/manage-users`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/order-history` | `/order-history`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/ongoing-orders` | `/ongoing-orders`; params?: Router.UnknownOutputParams; } | { pathname: `/auth/login`; params?: Router.UnknownOutputParams; } | { pathname: `/kitchen`; params?: Router.UnknownOutputParams; } | { pathname: `/edit-order/[id]`, params: Router.UnknownOutputParams & { id: string; } };
      href: Router.RelativePathString | Router.ExternalPathString | `/checkout${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/add-menu-item${`?${string}` | `#${string}` | ''}` | `/add-menu-item${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/create-user${`?${string}` | `#${string}` | ''}` | `/create-user${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/dashboard${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/edit-menu-item${`?${string}` | `#${string}` | ''}` | `/edit-menu-item${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/manage-users${`?${string}` | `#${string}` | ''}` | `/manage-users${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/order-history${`?${string}` | `#${string}` | ''}` | `/order-history${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/settings${`?${string}` | `#${string}` | ''}` | `/settings${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/ongoing-orders${`?${string}` | `#${string}` | ''}` | `/ongoing-orders${`?${string}` | `#${string}` | ''}` | `/auth/login${`?${string}` | `#${string}` | ''}` | `/kitchen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/checkout`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/add-menu-item` | `/add-menu-item`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/create-user` | `/create-user`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/dashboard` | `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/edit-menu-item` | `/edit-menu-item`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/manage-users` | `/manage-users`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/order-history` | `/order-history`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/settings` | `/settings`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/ongoing-orders` | `/ongoing-orders`; params?: Router.UnknownInputParams; } | { pathname: `/auth/login`; params?: Router.UnknownInputParams; } | { pathname: `/kitchen`; params?: Router.UnknownInputParams; } | `/edit-order/${Router.SingleRoutePart<T>}${`?${string}` | `#${string}` | ''}` | { pathname: `/edit-order/[id]`, params: Router.UnknownInputParams & { id: string | number; } };
    }
  }
}
